### ISSUE TITLE
Double precision format not rendered

### ISSUE THREAD

**Issue by qrpike** [polygon-io/ui-swagger#72]
When specifying a double format int, the UI does not make any visible representation of this. 

![image](https://user-images.githubusercontent.com/669468/85140769-b93b1080-b213-11ea-8a24-00aef06dfcb6.png)

```yaml
      o:
        type: integer
        format: double
        description: Open
        example: 102.87
      c:
        type: integer
        format: double
        description: Close
        example: 103.74
```
